default:
  golem_name: fd.dashboard
  golem_version: 0.0.0.9000
  app_prod: no
  dbname: fd_reports
  username: fd_reports_user
  password: 6Pb27%n_jH6J^@r&gJR-KbSxp--+8TBK
  host: rdsamazon.cbief3wnjkp9.eu-west-1.rds.amazonaws.com
  encoding: latin1
  table_leads_clean: bs_leads_clean
  table_leads_log: bs_leads_log
  plot.color: '#CA0813'
  plot.color.light: '#FC9272'
  line_thickness: 1.0
  spinner.color: '#0dc5c1'
  table_profiles_clean: bs_profiles_clean_tmp
  table_profiles_log: bs_profiles_log
  table_geo_timezones: geo_tz
production:
  app_prod: yes
dev:
  golem_wd: /Users/piotrgruszecki/Documents/GitHub/fd.dashboard
